backend:
  name: github
  # change repo to your git repository url
  branch: main
  repo: 
media_folder: static/assets
public_folder: /assets

collections:
  - name: Markdown File
    label: Markdown File
    label_singular: Markdown File
    folder: /posts/
    summary: '{{title}}'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BlueEconomy.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'description', name: 'description', widget: 'string', hint: 'Description will be here' }