backend:
  name: github
  # change repo to your git repository url
  branch: master
  repo: fahadsaleem164/next-with-netlify
media_folder: static/assets
public_folder: /assets

collections:
  - name: Markdown File
    label: Markdown File
    label_singular: Markdown File
    create: true
    delete: false 
    folder: /posts/
    summary: '{{title}}'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines for BlueEconomy.
    fields:
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Author', name: 'author', widget: 'string', tagname: 'h1' }
      - { label: 'description',  name: 'body', widget: 'markdown' , hint: 'Description will be here' }